version: '3.8'
services:
  config-service:
    image: config-service
    restart: always
    container_name: config-service
    ports:
      - '8090:8888'
    networks:
      - 'config-network'
networks:
  config-network:
    name: config-network
    driver: bridge
